---
  version: '3'
  services:
    minimal:
      build: .
      ports:
        - "127.0.0.1:8080:8080"
      restart: always
      environment:
        STATS_BASE_URL: 'http://127.0.0.1:8080'
        SITE_BASE_URL: 'http://127.0.0.1:8080'
      volumes:
        - .:/app